theme: jekyll-theme-minimal
title: CIT 281 - Project 1
description: I gained experience accessing my operating system's command line interface, working with CLI commands, and writing and executing non-web server Node.js JavaScript code.
